docs: Update requirements
strapi-community/website pull request #1
Opened 2023-01-19 10:17 UTC by boazpoolman

2023-01-19 13:01 UTC, Eventyret approved these changes

2023-01-19 13:08 UTC, Eventyret commented
Adding comment from @MattieBelt 
This:
> A valid submission should contain one of the following three pages to showcase all the components as a whole.
Should be

> A valid submission should contain all the components described below, this can be either on a single page or multiple pages.

2023-01-19 13:17 UTC, MattieBelt requested changes

2023-01-19 13:17 UTC, MattieBelt commented on README.md
> +A valid submission should contain **one** of the following three pages to showcase all the components as a whole.
```suggestion
A valid submission should contain all the components described below, this can be either on a single page or multiple pages.
```

2023-01-20 11:27 UTC, boazpoolman commented
@MattieBelt @Eventyret 
Made the change you mentioned. Should be good to go like this!

2023-01-20 11:29 UTC, Eventyret approved these changes

2023-01-20 11:34 UTC, MattieBelt approved these changes

2023-01-20 11:56 UTC, merged